DATABASE_URL = "sqlite:///./test.db"

EMAIL_REGEX = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"

TEST_DATABASE_URL = "sqlite:///./testing.db"

ACCESS_TOKEN_SECRET = "THISISASECRETKEY"
ACCESS_TOKEN_EXPIRE = 1

REFRESH_TOKEN_SECRET = "THISISAREFRESHSECRETKEY"
REFRESH_TOKEN_EXPIRE = 7